### ISSUE TITLE
Test why the website takes a long time to load

### ISSUE THREAD

**Issue by Zibethin** [AmericanRedCross/folder-view-dropbox#11]

**Comment by danbjoseph** [comment]
https://tools.pingdom.com/#!/bPeZgu/rcrcsims.org
page size is 4.0 MB
front banner is 1.1 MB (could be downsized/reduced-quality some to get smaller?)
world map json is 712kB (could be reduced by using topojson)

probably won't help in this case, but an interesting read here: http://www.macwright.org/2016/05/03/the-featherweight-website.html

**Comment by Zibethin** [comment]
Thanks Dan that is super useful

**Comment by danbjoseph** [comment]
site changed a lot when converted to jekyll and built with travis-ci
