### ISSUE TITLE
large images

### ISSUE THREAD

**Issue by dalekunce** [AmericanRedCross/folder-view-dropbox#3]
the OSM and HID logos are way way to big.

<img width="707" alt="screen shot 2017-02-08 at 11 25 18 am" src="https://cloud.githubusercontent.com/assets/1913857/22753536/4ae09fea-edf1-11e6-94a7-0a8c879997e9.png">

**Comment by Zibethin** [comment]
Here is the commit for it https://github.com/AmericanRedCross/sims-website/pull/2/commits/3f0d661308ffe920de5efec173e3d6c37ae29dcb .
