### ISSUE TITLE
footer is too big

### ISSUE THREAD

**Issue by dalekunce** [AmericanRedCross/folder-view-dropbox#4]
reduce the size of the footer. @Zibethin

**Comment by Zibethin** [comment]
changed in commit https://github.com/AmericanRedCross/sims-website/commit/377f5cb9cecc54432c0b7b7ce068a7cfb235e9c6

**Comment by dalekunce** [comment]
@Zibethin next time put "closes #<number of issue>" and it will automatically close it. Good work.
