### ISSUE TITLE
map autoupdating

### ISSUE THREAD

**Issue by dalekunce** [AmericanRedCross/folder-view-dropbox#6]
need to make an autoupdating google sheet that can be hit with an ajax query that does not have PII data. @pknight03 @Zibethin

**Comment by danbjoseph** [comment]
dashboard is created from
https://docs.google.com/spreadsheets/d/1u2ZH4VBOjH-Rk3p4g8yel1TsBvBuyzUfwAr9le36V_A/edit#gid=0
(not sure there is someone tasked with updating the sheet, but it's got no PII)
